spring:
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: Asia/Tokyo
  datasource:
    url: jdbc:mysql://localhost:3306/myApp_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      maxActive: 30
      maxIdle: 20
      minIdle: 10
      initialSize: 5