spring:
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: Asia/Tokyo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myApp_db
    username: root
    password: Ff3f7Z56)AiH
    schema: classpath:schema.sql
    data: classpath:data.sql
    tomcat:
      maxActive: 30
      maxIdle: 20
      minIdle: 10
      initialSize: 5
mybatis:
  configuration:
    map-underscore-to-camel-case: true
